# Generated by Django 3.1.5 on 2021-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_decimal',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Percentage'),
        ),
    ]
