# Generated by Django 3.1.5 on 2021-01-21 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20210121_1912'),
        ('matches', '0002_auto_20210110_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('liked', models.BooleanField(verbose_name='Liked')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.location', verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'LocationMatch',
                'verbose_name_plural': 'LocationMatchs',
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('liked', models.BooleanField(verbose_name='Liked')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'jobmatch',
                'verbose_name_plural': 'jobmatchs',
            },
        ),
        migrations.CreateModel(
            name='EmployerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('liked', models.BooleanField(verbose_name='Liked')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employer', verbose_name='Employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'EmployerMatch',
                'verbose_name_plural': 'EmployerMatchs',
            },
        ),
    ]
