# Generated by Django 3.1.5 on 2021-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_employermatch_jobmatch_locationmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employermatch',
            name='liked',
            field=models.NullBooleanField(verbose_name='Liked'),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='liked',
            field=models.NullBooleanField(verbose_name='Liked'),
        ),
        migrations.AlterField(
            model_name='locationmatch',
            name='liked',
            field=models.NullBooleanField(verbose_name='Liked'),
        ),
    ]
