# Generated by Django 3.1.5 on 2021-01-22 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20210121_1912'),
        ('matches', '0005_auto_20210121_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('liked', models.BooleanField(null=True, verbose_name='Liked')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'PositionMatch',
                'verbose_name_plural': 'PositionMatchs',
            },
        ),
        migrations.DeleteModel(
            name='JobMatch',
        ),
    ]
