# Generated by Django 3.1.5 on 2021-01-11 22:25

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_location, verbose_name='Picture'),
        ),
    ]
