# Generated by Django 3.1.5 on 2021-01-08 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20210107_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_answer_importance', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'ver important'), ('Somewhat Important', 'somewhat important'), ('Not important', 'not important')], max_length=50, verbose_name='My Answer')),
                ('their_answer_importance', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'ver important'), ('Somewhat Important', 'somewhat important'), ('Not important', 'not important')], max_length=50, verbose_name='Their answer importants')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Timestamp')),
                ('my_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='questions.answer', verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Question')),
                ('their_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_answer', to='questions.answer', verbose_name='Their answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'useranswer',
                'verbose_name_plural': 'useranswers',
            },
        ),
    ]
