# Generated by Django 3.1.5 on 2021-01-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'ver important'), ('Somewhat Important', 'somewhat important'), ('Not important', 'not important')], max_length=50, verbose_name='My Answer Importance'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_answer', to='questions.answer', verbose_name='Their answer'),
        ),
    ]
