# Generated by Django 3.1.5 on 2021-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210108_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not important', 'Not important')], max_length=50, verbose_name='My Answer Importance'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='my_points',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='My points'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_answer_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not important', 'Not important')], max_length=50, verbose_name='Their answer importants'),
        ),
    ]
