# Generated by Django 3.1.5 on 2021-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210109_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_points',
            field=models.IntegerField(default=-1, verbose_name='My points'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_points',
            field=models.IntegerField(default=-1, verbose_name='My points'),
        ),
    ]
