# Generated by Django 3.1.5 on 2021-01-19 19:26

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210119_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
