# Generated by Django 3.1.5 on 2021-01-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_employer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='state',
        ),
    ]
