# Generated by Django 3.1.5 on 2021-01-22 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='userlike',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='Liked users'),
        ),
    ]
